baseURL: /
languageCode: en-US
defaultContentLanguage: en
title: Hugo Learn Documentation
theme: hugo-theme-learn
metaDataFormat: yaml
defaultContentLanguageInSubdir: no
params:
  author: Mathieu Cornic
  customMermaidURL: https://unpkg.com/mermaid@8.8.0/dist/mermaid.min.js
  description: Documentation for Hugo Learn Theme
  disableBreadcrumb: no
  disableLandingPageButton: no
  disableMermaid: no
  disableNextPrev: no
  editURL: https://github.com/matcornic/hugo-theme-learn/edit/master/exampleSite/content/
  showVisitedLinks: no
  titleSeparator: '::'
outputs:
  home:
    - HTML
    - RSS
    - JSON
Languages:
  en:
    landingPageName: <i class='fas fa-home'></i> Main Site
    landingPageURL: https://thomasjwise.com/ 
    languageName: English
    menu:
      shortcuts:
        - identifier: ds
          name: <i class='fab fa-fw fa-github'></i> Learn Theme - GitHub repo
          url: https://github.com/matcornic/hugo-theme-learn
          weight: 10
        - identifier: hugodoc
          name: <i class='fas fa-fw fa-bookmark'></i> Learn Theme - Hugo Documentation
          url: https://gohugo.io/
          weight: 20
        - name: <i class='fas fa-fw fa-bullhorn'></i> Learn Theme - Credits
          url: /credits
          weight: 30
